// Copyright 2026 Query Farm LLC - https://query.farm

package farm.query.vgi.internal;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * Cross-SDK conformance for the split-token envelope.
 *
 * <p>The envelope is the one part of the splits change where five independent
 * implementations can silently diverge AND where diverging is a vulnerability.
 * Behavioural tests miss that: each SDK is self-consistent, so a disagreement on
 * {@code anchor_len} endianness or fingerprint truncation only surfaces when a
 * token crosses SDKs. These vectors are byte-level and shared — every SDK parses
 * them and reproduces the deterministic ones byte-for-byte.</p>
 *
 * <p><b>One vector is deliberately excluded here.</b> {@code valid_sealed} has an
 * XChaCha20-Poly1305 payload, while this SDK seals with the ChaCha20-Poly1305 its
 * attach and transaction envelopes already use. That is sound — a split token is
 * minted <em>and</em> verified by the same worker, so it never opens one another
 * SDK sealed — and the test states it rather than skipping it silently. Every
 * plaintext-header vector, including the security-critical alg:none case, is
 * checked here exactly as in the other SDKs.</p>
 */
class SplitTokenConformanceTest {

    private record Vector(String name, String verdict, String note, boolean workerKeyed) {}

    private static byte[] resource(String name) {
        try (InputStream in = SplitTokenConformanceTest.class
                .getResourceAsStream("/split_tokens/" + name)) {
            assertNotNull(in, "missing shared fixture: " + name);
            return in.readAllBytes();
        } catch (IOException e) {
            throw new IllegalStateException("reading fixture " + name, e);
        }
    }

    private static String manifest() {
        return new String(resource("manifest.json"), StandardCharsets.UTF_8);
    }

    /** Pull one top-level string field out of the manifest. */
    private static String field(String key) {
        Matcher m = Pattern.compile("\"" + key + "\"\\s*:\\s*\"([^\"]*)\"").matcher(manifest());
        assertTrue(m.find(), "manifest has no " + key);
        return m.group(1);
    }

    /**
     * Parse the case list. A hand-rolled reader rather than a JSON dependency:
     * the manifest is a fixed shape generated by the reference SDK, and adding a
     * parser dependency to assert nine records would be the larger change.
     */
    private static List<Vector> vectors() {
        List<Vector> out = new ArrayList<>();
        Matcher m = Pattern.compile(
                "\\{\\s*\"name\"\\s*:\\s*\"([^\"]+)\""
                        + ".*?\"verdict\"\\s*:\\s*\"([^\"]+)\""
                        + ".*?\"note\"\\s*:\\s*\"((?:[^\"\\\\]|\\\\.)*)\""
                        + ".*?\"worker_keyed\"\\s*:\\s*(true|false)",
                Pattern.DOTALL).matcher(manifest());
        while (m.find()) {
            out.add(new Vector(m.group(1), m.group(2), m.group(3), Boolean.parseBoolean(m.group(4))));
        }
        assertTrue(out.size() >= 8, "expected the full shared vector set, got " + out.size());
        return out;
    }

    private static byte[] fromHex(String hex) {
        byte[] out = new byte[hex.length() / 2];
        for (int i = 0; i < out.length; i++) {
            out[i] = (byte) Integer.parseInt(hex.substring(i * 2, i * 2 + 2), 16);
        }
        return out;
    }

    @Test
    void sharedVectorsReachTheirRecordedVerdict() {
        assertEquals(1, Integer.parseInt(
                        Pattern.compile("\"format_version\"\\s*:\\s*(\\d+)").matcher(manifest())
                                .results().findFirst().orElseThrow().group(1)),
                "fixture format_version disagrees with this SDK");

        byte[] key = fromHex(field("key_hex"));
        byte[] fingerprint = fromHex(field("fingerprint_hex"));
        byte[] anchor = fromHex(field("anchor_hex"));
        byte[] payload = field("payload").getBytes(StandardCharsets.UTF_8);

        for (Vector v : vectors()) {
            // See the class comment: this vector's payload uses a different AEAD
            // construction here, by design.
            if (v.name().equals("valid_sealed")) {
                continue;
            }
            byte[] token = resource(v.name() + ".bin");
            // The manifest states the key state rather than each SDK inferring
            // it: the alg:none vector is a structurally VALID unsealed token
            // whose whole point is that a KEYED worker refuses it, so guessing
            // from the token would test the opposite of the rule.
            byte[] workerKey = v.workerKeyed() ? key : null;

            if (v.verdict().equals("ok")) {
                assertArrayEquals(payload,
                        SplitToken.open(token, workerKey, null, fingerprint, anchor),
                        v.name() + ": " + v.note());
                continue;
            }

            SplitToken.SplitTokenException e = assertThrows(
                    SplitToken.SplitTokenException.class,
                    () -> SplitToken.open(token, workerKey, null, fingerprint, anchor),
                    v.name() + " was ACCEPTED (" + v.note() + ")");
            assertEquals(v.verdict(), e.kind(), v.name() + ": " + v.note());
        }
    }

    @Test
    void theDeterministicVectorIsReproducedByteForByte() {
        // Proves the STAMPING side agrees too: a parser can be permissive enough
        // to accept another SDK's bytes while emitting bytes that SDK would
        // reject. Only the unsealed vector applies — a sealed token carries a
        // random nonce.
        byte[] got = SplitToken.build(
                field("payload").getBytes(StandardCharsets.UTF_8),
                fromHex(field("fingerprint_hex")),
                fromHex(field("anchor_hex")),
                null, null);
        assertArrayEquals(resource("valid_unsealed.bin"), got,
                "valid_unsealed bytes differ from the shared vector");
    }

    @Test
    void aKeyedWorkerRefusesAnUnsealedToken() {
        // The alg:none rule stated directly rather than via a fixture name,
        // because it is the rule most likely to be "simplified" away by a later
        // reader: flags is attacker-controlled plaintext, so a parser that trusts
        // bit 0 lets any caller forge a split against a fully-keyed worker.
        byte[] key = new byte[32];
        java.util.Arrays.fill(key, (byte) 0x2a);
        byte[] fingerprint = new byte[16];
        java.util.Arrays.fill(fingerprint, (byte) 0x07);
        byte[] anchor = SplitToken.anchor(47);

        byte[] forged = SplitToken.build("file=evil".getBytes(StandardCharsets.UTF_8),
                fingerprint, anchor, null, null);
        assertThrows(SplitToken.SplitTokenException.class,
                () -> SplitToken.open(forged, key, null, fingerprint, null),
                "a keyed worker accepted an UNSEALED token: alg:none downgrade");

        byte[] sealed = SplitToken.build("file=ok".getBytes(StandardCharsets.UTF_8),
                fingerprint, anchor, key, null);
        assertThrows(SplitToken.SplitTokenException.class,
                () -> SplitToken.open(sealed, null, null, fingerprint, null),
                "a keyless worker claimed to open a SEALED token");

        assertArrayEquals("file=ok".getBytes(StandardCharsets.UTF_8),
                SplitToken.open(sealed, key, null, fingerprint, null));

        byte[] wrong = new byte[32];
        java.util.Arrays.fill(wrong, (byte) 0x2b);
        assertThrows(RuntimeException.class,
                () -> SplitToken.open(sealed, wrong, null, fingerprint, null),
                "a token opened under the WRONG key");
    }

    @Test
    void expiryAndInvalidityAreDistinguishable() {
        // Only one of them means "re-run the query", and keeping the anchor in
        // the PLAINTEXT header is what makes the distinction expressible at all —
        // inside the AAD both would collapse into one tag-check failure.
        byte[] fingerprint = new byte[16];
        java.util.Arrays.fill(fingerprint, (byte) 0x09);
        byte[] old = SplitToken.anchor(47);
        byte[] current = SplitToken.anchor(48);

        byte[] token = SplitToken.build("file=1".getBytes(StandardCharsets.UTF_8),
                fingerprint, old, null, null);

        SplitToken.SplitTokenException stale = assertThrows(
                SplitToken.SplitTokenException.class,
                () -> SplitToken.open(token, null, null, fingerprint, current));
        assertEquals(SplitToken.KIND_EXPIRED, stale.kind());

        byte[] other = new byte[16];
        java.util.Arrays.fill(other, (byte) 0x0a);
        SplitToken.SplitTokenException wrongBind = assertThrows(
                SplitToken.SplitTokenException.class,
                () -> SplitToken.open(token, null, null, other, old));
        assertEquals(SplitToken.KIND_INVALID, wrongBind.kind());
    }

    @Test
    void theFingerprintIsStableForTheSameBind() {
        // It only has to be self-consistent within one worker — it is minted and
        // verified by the same process, and no client computes it — but it must
        // be STABLE, or a token minted at plan time fails at redemption.
        byte[] a = SplitToken.bindFingerprint("main", "scan", new byte[] {1, 2}, new byte[0], new byte[0]);
        byte[] b = SplitToken.bindFingerprint("main", "scan", new byte[] {1, 2}, new byte[0], new byte[0]);
        assertArrayEquals(a, b);
        assertEquals(16, a.length);

        byte[] other = SplitToken.bindFingerprint("main", "other", new byte[] {1, 2},
                new byte[0], new byte[0]);
        if (java.util.Arrays.equals(a, other)) {
            fail("a different function name produced the same fingerprint");
        }
    }
}
