// GENERATED by vgi.codegen.java_types. DO NOT EDIT BY HAND.
//
// Generator: python -m vgi.codegen.java_types CatalogContentsResponse v1
// Content hash: ca1ec2025da2
//
// To regenerate:
//   uv run --project ~/Development/vgi-python python scripts/regen_generated.py

// Copyright 2025, 2026 Query Farm LLC - https://query.farm

package farm.query.vgi.protocol;

import farm.query.vgirpc.schema.ArrowSerializableRecord;
import farm.query.vgirpc.schema.Nullable;

import java.util.List;

/**
 * Response for {@code catalog_contents()}: the whole catalog in one result.
 *
 * <p>Protocol type {@code vgi.protocol.CatalogContentsResponse}, generated from its
 * {@code ARROW_SCHEMA}: component order is column order and {@code @Nullable} is wire nullability.
 *
 * @param catalog_version The catalog version the snapshot was taken at. Worker-defined and only
 *        meaningful within the session that requested it.
 * @param etag Opaque validator for this snapshot, to send back as {@code if_none_match}. Null means
 *        the worker does not revalidate (and ignores {@code if_none_match}).
 * @param not_modified {@code True} when the request's {@code if_none_match} equals the current
 *        {@code etag}: {@code schemas} is then empty and the client keeps the contents it has.
 * @param schemas One {@code SchemaContents} struct per schema, parents before children. Empty when
 *        {@code not_modified}.
 */
public record CatalogContentsResponse(
        long catalog_version,
        @Nullable String etag,
        boolean not_modified,
        List<SchemaContents> schemas) implements ArrowSerializableRecord {
}
