// GENERATED by vgi.codegen.java_types. DO NOT EDIT BY HAND.
//
// Generator: python -m vgi.codegen.java_types CatalogAttachResult v1
// Content hash: d5b6d5e269f5
//
// To regenerate:
//   uv run --project ~/Development/vgi-python python scripts/regen_generated.py

// Copyright 2025, 2026 Query Farm LLC - https://query.farm

package farm.query.vgi.protocol;

import farm.query.vgirpc.schema.ArrowSerializableRecord;
import farm.query.vgirpc.schema.Nullable;

import java.util.List;
import java.util.Map;

/**
 * Result from attaching to a catalog.
 *
 * <p>Protocol type {@code vgi.catalog.catalog_interface.CatalogAttachResult}, generated from its
 * {@code ARROW_SCHEMA}: component order is column order and {@code @Nullable} is wire nullability.
 *
 * @param attach_opaque_data The unique id for the attached catalog.
 * @param supports_transactions Indicate if the worker supports transactions or not. If false, all
 *        transaction related methods will not be called and all transaction_opaque_data parameters
 *        will be None.
 * @param supports_time_travel Indicate if tables support time travel.
 * @param catalog_version_frozen Indicate that the catalog version id is frozen and the schema and
 *        object information will not change.
 * @param catalog_version The initial catalog version, it increments when schemas, tables or other
 *        objects change.
 * @param attach_opaque_data_required Indicate if the attach_opaque_data must be persisted across
 *        commands. True: Catalog is stateful; attach_opaque_data represents a session. False:
 *        Catalog is stateless; CLI can auto-attach on each command.
 * @param default_schema The name of the default schema for this catalog.
 * @param settings Extension options (settings) exposed by this catalog/worker. Each ExtensionOption
 *        is serialized as bytes for Arrow compatibility.
 * @param secret_types Secret types registered with DuckDB's SecretManager. Each SecretTypeSpec is
 *        serialized as bytes for Arrow compatibility.
 * @param attach_catalogs Companion catalogs the client should ATTACH alongside this VGI catalog
 *        (lakehouse federation). Each {@code AttachCatalogInfo} is serialized as bytes for Arrow
 *        compatibility. Attached at VGI-attach time; detached (refcounted) on DETACH. See
 *        {@code AttachCatalogInfo} and {@code docs/companion_catalogs.md}.
 * @param comment Optional comment describing this catalog/database.
 * @param tags Optional key-value tags associated with this catalog/database.
 * @param supports_column_statistics Whether any tables in this catalog can provide column
 *        statistics. Global gate — if False, GetStatistics() returns nullptr for all tables.
 * @param global_functions Functions this catalog asks the client to publish into the *global*
 *        function namespace (DuckDB's {@code system.main}), in addition to their normal
 *        schema-qualified registration. Each {@code FunctionInfo} is serialized as bytes for Arrow
 *        compatibility. {@code name}/{@code schema_path} stay the real dispatch coordinates — the
 *        client derives the globally visible name by applying {@code global_function_prefix}.
 *        Registration is first-attach-wins: a name already owned by a different worker is skipped
 *        (logged), and the ATTACH still succeeds. Empty list = this catalog publishes nothing
 *        globally. See {@code docs/global-functions.md}.
 * @param global_function_prefix Prefix applied to every {@code global_functions} entry to form its
 *        globally visible name ({@code &lt;prefix&gt;_&lt;name&gt;}). Empty string = publish bare
 *        names, which is more collision-prone; prefer a prefix that identifies the worker.
 * @param resolved_data_version Concrete data version the worker resolved for this attach.
 *        {@code None} = worker has no opinion or the request omitted data_version_spec.
 * @param resolved_implementation_version Concrete implementation version the worker resolved for
 *        this attach. {@code None} = worker has no opinion or the request omitted
 *        implementation_version.
 * @param supports_catalog_contents Whether the client may load the whole catalog with one
 *        {@code catalog_contents} call instead of {@code catalog_schemas} plus a
 *        {@code catalog_schema_contents_*} call per schema and kind. Older workers omit it and read
 *        as {@code False}.
 */
public record CatalogAttachResult(
        byte[] attach_opaque_data,
        boolean supports_transactions,
        boolean supports_time_travel,
        boolean catalog_version_frozen,
        long catalog_version,
        boolean attach_opaque_data_required,
        String default_schema,
        List<byte[]> settings,
        List<byte[]> secret_types,
        List<byte[]> attach_catalogs,
        @Nullable String comment,
        Map<String, String> tags,
        boolean supports_column_statistics,
        List<byte[]> global_functions,
        String global_function_prefix,
        @Nullable String resolved_data_version,
        @Nullable String resolved_implementation_version,
        boolean supports_catalog_contents) implements ArrowSerializableRecord {
}
