// GENERATED by vgi.codegen.java_types. DO NOT EDIT BY HAND.
//
// Generator: python -m vgi.codegen.java_types CatalogContentsResponse v1
// Content hash: c7a403469331
//
// To regenerate:
//   uv run --project ~/Development/vgi-python python scripts/regen_generated.py

// Copyright 2025, 2026 Query Farm LLC - https://query.farm

package farm.query.vgi.protocol;

import farm.query.vgirpc.schema.ArrowSerializableRecord;

import java.util.List;

/**
 * Response for {@code catalog_contents()}: the whole catalog in one result.
 *
 * <p>Protocol type {@code vgi.protocol.CatalogContentsResponse}, generated from its
 * {@code ARROW_SCHEMA}: component order is column order and {@code @Nullable} is wire nullability.
 *
 * @param catalog_version The catalog version the snapshot was taken at. Worker-defined and only
 *        meaningful within the session that requested it.
 * @param schemas One IPC-serialized {@code SchemaContents} per schema, parents before children.
 */
public record CatalogContentsResponse(
        long catalog_version,
        List<byte[]> schemas) implements ArrowSerializableRecord {
}
