// GENERATED by vgi.codegen.java_types. DO NOT EDIT BY HAND.
//
// Generator: python -m vgi.codegen.java_types SchemaContents v1
// Content hash: 6f4603d839e7
//
// To regenerate:
//   uv run --project ~/Development/vgi-python python scripts/regen_generated.py

// Copyright 2025, 2026 Query Farm LLC - https://query.farm

package farm.query.vgi.protocol;

import farm.query.vgirpc.schema.ArrowSerializableRecord;

import java.util.List;

/**
 * One schema and everything in it, as carried by {@code catalog_contents()}.
 *
 * <p>Every item is byte-for-byte what the matching per-schema RPC returns in its {@code items}
 * list, so a client decodes them with the decoders it already has. Each kind is complete: an empty
 * list means the schema has none of that kind.
 *
 * <p>Protocol type {@code vgi.protocol.SchemaContents}, generated from its {@code ARROW_SCHEMA}:
 * component order is column order and {@code @Nullable} is wire nullability.
 *
 * @param schema The schema's {@code SchemaInfo} item (a {@code catalog_schemas} entry).
 * @param tables {@code TableInfo} items ({@code catalog_schema_contents_tables}).
 * @param views {@code ViewInfo} items ({@code catalog_schema_contents_views}).
 * @param scalar_functions {@code FunctionInfo} items, {@code SCALAR_FUNCTION}.
 * @param aggregate_functions {@code FunctionInfo} items, {@code AGGREGATE_FUNCTION}.
 * @param table_functions {@code FunctionInfo} items, {@code TABLE_FUNCTION}.
 * @param scalar_macros {@code MacroInfo} items, {@code SCALAR_MACRO}.
 * @param table_macros {@code MacroInfo} items, {@code TABLE_MACRO}.
 * @param indexes {@code IndexInfo} items ({@code catalog_schema_contents_indexes}).
 */
public record SchemaContents(
        byte[] schema,
        List<byte[]> tables,
        List<byte[]> views,
        List<byte[]> scalar_functions,
        List<byte[]> aggregate_functions,
        List<byte[]> table_functions,
        List<byte[]> scalar_macros,
        List<byte[]> table_macros,
        List<byte[]> indexes) implements ArrowSerializableRecord {
}
