// Copyright 2026 Query Farm LLC - https://query.farm

package farm.query.vgi;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import farm.query.vgi.internal.BatchUtil;
import farm.query.vgi.protocol.CatalogAttachRequest;
import farm.query.vgirpc.AuthContext;
import farm.query.vgirpc.HasErrorKind;
import farm.query.vgirpc.wire.Allocators;
import org.apache.arrow.vector.FieldVector;
import org.apache.arrow.vector.VarCharVector;
import org.apache.arrow.vector.VectorSchemaRoot;
import org.apache.arrow.vector.types.pojo.ArrowType;
import org.apache.arrow.vector.types.pojo.Field;
import org.apache.arrow.vector.types.pojo.FieldType;
import org.apache.arrow.vector.types.pojo.Schema;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestFactory;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Base64;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * The cross-SDK attach-ticket vectors ({@code attach_ticket_vectors.json}, generated by
 * vgi-python's {@code scripts/gen_attach_ticket_vectors.py}): every mint token reproduced byte for
 * byte, every accept opened to exactly its claims, every reject refused with exactly its error
 * kind, and every redeem case applied as {@code catalog_attach} does.
 */
final class AttachTicketVectorsTest {

    private static final JsonObject VECTORS = load();
    private static final JsonObject DEFAULTS = VECTORS.getAsJsonObject("defaults");

    private static JsonObject load() {
        try (InputStream in = AttachTicketVectorsTest.class.getResourceAsStream(
                "/attach_tickets/attach_ticket_vectors.json")) {
            assertNotNull(in, "attach_ticket_vectors.json is not on the test classpath");
            return JsonParser.parseString(new String(in.readAllBytes(), StandardCharsets.UTF_8)).getAsJsonObject();
        } catch (java.io.IOException e) {
            throw new IllegalStateException(e);
        }
    }

    private static byte[] b64(String s) {
        return Base64.getDecoder().decode(s);
    }

    private static byte[] key(JsonObject c) {
        return b64(c.has("signing_key_b64") ? c.get("signing_key_b64").getAsString()
                : DEFAULTS.get("signing_key_b64").getAsString());
    }

    private static long now(JsonObject c) {
        return c.has("now") ? c.get("now").getAsLong() : DEFAULTS.get("now").getAsLong();
    }

    private static List<JsonObject> cases(String section) {
        List<JsonObject> out = new ArrayList<>();
        for (JsonElement e : VECTORS.getAsJsonArray(section)) out.add(e.getAsJsonObject());
        return out;
    }

    private static String str(JsonObject c, String field) {
        return c.get(field).getAsString();
    }

    @Test
    void theFormatConstantsMatch() {
        assertEquals(DEFAULTS.get("clock_skew_seconds").getAsLong(), AttachTickets.CLOCK_SKEW_SECONDS);
        assertEquals(DEFAULTS.get("max_options_bytes").getAsInt(), AttachTickets.MAX_OPTIONS_BYTES);
        assertEquals(DEFAULTS.get("max_ticket_chars").getAsInt(), AttachTickets.MAX_TICKET_CHARS);
        assertEquals(DEFAULTS.get("envelope_version").getAsInt(), AttachTickets.ENVELOPE_VERSION);
        assertTrue(cases("mint").size() >= 3 && cases("reject").size() >= 29 && cases("redeem").size() >= 9);
    }

    @TestFactory
    List<DynamicTest> mint() {
        List<DynamicTest> tests = new ArrayList<>();
        for (JsonObject c : cases("mint")) {
            tests.add(DynamicTest.dynamicTest(str(c, "name"), () -> {
                byte[] options = b64(str(c, "options_ipc_b64"));
                AttachTickets.Claims claims = new AttachTickets.Claims(c.get("issued_at").getAsLong(),
                        c.get("expires_at").getAsLong(), str(c, "ticket_id"), str(c, "catalog_name"),
                        str(c, "data_version_spec"), str(c, "implementation_version"), options);
                assertEquals(str(c, "payload_hex"), HexFormat.of().formatHex(AttachTickets.encodePayload(claims)));
                assertEquals(str(c, "aad_hex"), HexFormat.of().formatHex(AttachTickets.aad(str(c, "principal"))));
                String token = AttachTickets.mint(key(c), str(c, "principal"), str(c, "catalog_name"), options,
                        str(c, "data_version_spec"), str(c, "implementation_version"),
                        c.get("issued_at").getAsLong(), c.get("expires_at").getAsLong(),
                        str(c, "ticket_id"), HexFormat.of().parseHex(str(c, "nonce_hex")));
                assertEquals(str(c, "token"), token);
            }));
        }
        return tests;
    }

    @TestFactory
    List<DynamicTest> accept() {
        List<DynamicTest> tests = new ArrayList<>();
        for (JsonObject c : cases("accept")) {
            tests.add(DynamicTest.dynamicTest(str(c, "name"), () -> {
                AttachTickets.Claims got = AttachTickets.open(key(c), str(c, "token"), str(c, "principal"), now(c));
                JsonObject want = c.getAsJsonObject("claims");
                assertEquals(want.get("issued_at").getAsLong(), got.issuedAt());
                assertEquals(want.get("expires_at").getAsLong(), got.expiresAt());
                assertEquals(str(want, "ticket_id"), got.ticketId());
                assertEquals(str(want, "catalog_name"), got.catalogName());
                assertEquals(str(want, "data_version_spec"), got.dataVersionSpec());
                assertEquals(str(want, "implementation_version"), got.implementationVersion());
                assertArrayEquals(b64(str(want, "options_ipc_b64")), got.optionsIpc());
            }));
        }
        return tests;
    }

    @TestFactory
    List<DynamicTest> reject() {
        List<DynamicTest> tests = new ArrayList<>();
        for (JsonObject c : cases("reject")) {
            tests.add(DynamicTest.dynamicTest(str(c, "name"), () -> {
                RuntimeException e = assertThrows(RuntimeException.class,
                        () -> AttachTickets.open(key(c), str(c, "token"), str(c, "principal"), now(c)));
                assertTrue(e instanceof HasErrorKind, e.toString());
                assertEquals(str(c, "error_kind"), ((HasErrorKind) e).errorKind(), e.toString());
                // Never echo the ticket.
                String token = str(c, "token");
                if (token.length() > 16) {
                    assertTrue(!e.getMessage().contains(token.substring(6, 16)), e.getMessage());
                }
            }));
        }
        return tests;
    }

    @TestFactory
    List<DynamicTest> redeem() {
        List<DynamicTest> tests = new ArrayList<>();
        for (JsonObject c : cases("redeem")) {
            tests.add(DynamicTest.dynamicTest(str(c, "name"), () -> {
                Map<String, String> options = new LinkedHashMap<>();
                for (var e : c.getAsJsonObject("options").entrySet()) options.put(e.getKey(), e.getValue().getAsString());
                byte[] client = new byte[] {7, 7};
                CatalogAttachRequest request = new CatalogAttachRequest("not_the_sealed_name",
                        optionsIpc(options), "ignored", "ignored", client);
                String principal = str(c, "principal");
                AuthContext auth = principal.isEmpty() ? AuthContext.ANONYMOUS
                        : new AuthContext("grant", true, principal, Map.of());
                if (c.has("error_kind")) {
                    RuntimeException e = assertThrows(RuntimeException.class,
                            () -> AttachTickets.redeem(request, key(c), auth, now(c)));
                    assertEquals(str(c, "error_kind"), ((HasErrorKind) e).errorKind(), e.toString());
                    return;
                }
                CatalogAttachRequest got = AttachTickets.redeem(request, key(c), auth, now(c));
                if (c.get("result").isJsonNull()) {
                    assertNull(got, "a request without a ticket is untouched");
                    return;
                }
                JsonObject want = c.getAsJsonObject("result");
                assertEquals(str(want, "catalog_name"), got.name());
                assertEquals(nullable(want, "data_version_spec"), got.data_version_spec());
                assertEquals(nullable(want, "implementation_version"), got.implementation_version());
                assertArrayEquals(client, got.client_capabilities(), "client_capabilities is kept");
                Map<String, String> wantOptions = new LinkedHashMap<>();
                for (var e : want.getAsJsonObject("options").entrySet()) {
                    wantOptions.put(e.getKey(), e.getValue().getAsString());
                }
                assertEquals(wantOptions, decodeOptions(got.options()));
            }));
        }
        return tests;
    }

    @Test
    void aWorkerWithoutAKeyRefusesEveryTicket() {
        JsonObject c = cases("redeem").get(0);
        Map<String, String> options = Map.of(AttachTickets.OPTION, c.getAsJsonObject("options")
                .get(AttachTickets.OPTION).getAsString());
        CatalogAttachRequest request = CatalogAttachRequest.of("x", optionsIpc(options), null, null);
        AttachTicketInvalidError e = assertThrows(AttachTicketInvalidError.class,
                () -> AttachTickets.redeem(request, null, new AuthContext("grant", true, "alice", Map.of()), now(c)));
        assertEquals(AttachTicketInvalidError.KIND, e.errorKind());
    }

    @Test
    void theReservedOptionNameCannotBeDeclared() {
        for (String name : List.of("vgi_attach_ticket", "VGI_Attach_Ticket")) {
            IllegalArgumentException e = assertThrows(IllegalArgumentException.class,
                    () -> AttachOptionSpec.of(name, "x", new ArrowType.Utf8(), null));
            assertTrue(e.getMessage().contains("reserved"), e.getMessage());
        }
        AttachOptionSpec.of("vgi_attach_tickets", "a different name", new ArrowType.Utf8(), null);
    }

    @Test
    void aFreshMintRoundTrips() {
        byte[] key = "short operator key".getBytes(StandardCharsets.UTF_8);
        String t1 = AttachTickets.mint(key, "alice", "c", new byte[0], "", "", 100, 0);
        String t2 = AttachTickets.mint(key, "alice", "c", new byte[0], "", "", 100, 0);
        assertTrue(!t1.equals(t2), "a fresh nonce and id per ticket");
        assertEquals("c", AttachTickets.open(key, t1, "alice", 1e12).catalogName());
        assertThrows(IllegalArgumentException.class,
                () -> AttachTickets.mint(key, "", "c", new byte[0], "", "", 100, 0));
        assertThrows(IllegalArgumentException.class,
                () -> AttachTickets.mint(key, "alice", "c", new byte[0], "", "", 100, 100));
    }

    private static String nullable(JsonObject o, String field) {
        return o.get(field).isJsonNull() ? null : o.get(field).getAsString();
    }

    /** A one-row record of utf8 columns, in map order. */
    static byte[] optionsIpc(Map<String, String> options) {
        List<Field> fields = new ArrayList<>();
        for (String name : options.keySet()) fields.add(new Field(name, FieldType.nullable(new ArrowType.Utf8()), null));
        try (VectorSchemaRoot root = VectorSchemaRoot.create(new Schema(fields), Allocators.root())) {
            root.allocateNew();
            int i = 0;
            for (String value : options.values()) {
                ((VarCharVector) root.getVector(i++)).setSafe(0, value.getBytes(StandardCharsets.UTF_8));
            }
            root.setRowCount(1);
            return BatchUtil.writeSingleBatch(root);
        }
    }

    static Map<String, String> decodeOptions(byte[] ipc) {
        Map<String, String> out = new LinkedHashMap<>();
        if (ipc == null) return out;
        BatchUtil.withReadBatch(ipc, Allocators.root(), root -> {
            for (FieldVector v : root.getFieldVectors()) {
                if (!(v instanceof VarCharVector s)) fail("option " + v.getField() + " is not utf8");
                out.put(v.getField().getName(), new String(((VarCharVector) v).get(0), StandardCharsets.UTF_8));
            }
            return null;
        });
        return out;
    }
}
