// GENERATED by vgi.codegen.java_registry. DO NOT EDIT BY HAND.
//
// Generator: python -m vgi.codegen.java_registry v1
// Content hash: 6cbb8a064947
//
// To regenerate:
//   uv run --project ~/Development/vgi-python python scripts/regen_generated.py

// Copyright 2025, 2026 Query Farm LLC - https://query.farm

package farm.query.vgi;

import farm.query.vgi.protocol.AggregateBindRequest;
import farm.query.vgi.protocol.AggregateBindResponse;
import farm.query.vgi.protocol.AggregateCombineRequest;
import farm.query.vgi.protocol.AggregateCombineResponse;
import farm.query.vgi.protocol.AggregateDestructorRequest;
import farm.query.vgi.protocol.AggregateDestructorResponse;
import farm.query.vgi.protocol.AggregateFinalizeRequest;
import farm.query.vgi.protocol.AggregateFinalizeResponse;
import farm.query.vgi.protocol.AggregateUpdateRequest;
import farm.query.vgi.protocol.AggregateUpdateResponse;
import farm.query.vgi.protocol.BindRequest;
import farm.query.vgi.protocol.BindResponse;
import farm.query.vgi.protocol.CardinalityResponse;
import farm.query.vgi.protocol.CatalogAttachRequest;
import farm.query.vgi.protocol.CatalogAttachResult;
import farm.query.vgi.protocol.CatalogContentsResponse;
import farm.query.vgi.protocol.CatalogVersionResponse;
import farm.query.vgi.protocol.DynamicToStringResponse;
import farm.query.vgi.protocol.GlobalInitResponse;
import farm.query.vgi.protocol.InitRequest;
import farm.query.vgi.protocol.ItemsResponse;
import farm.query.vgi.protocol.PlanResponse;
import farm.query.vgi.protocol.TableBufferingCombineRequest;
import farm.query.vgi.protocol.TableBufferingCombineResponse;
import farm.query.vgi.protocol.TableBufferingDestructorRequest;
import farm.query.vgi.protocol.TableBufferingDestructorResponse;
import farm.query.vgi.protocol.TableBufferingProcessRequest;
import farm.query.vgi.protocol.TableBufferingProcessResponse;
import farm.query.vgi.protocol.TableScanFunctionGetResponse;
import farm.query.vgi.protocol.TransactionBeginResponse;
import farm.query.vgirpc.CallContext;
import farm.query.vgirpc.MethodNotImplementedError;
import farm.query.vgirpc.RpcStream;
import farm.query.vgirpc.StreamState;
import farm.query.vgirpc.schema.ArrowField;
import farm.query.vgirpc.schema.ArrowFieldType;
import farm.query.vgirpc.schema.Nullable;
import farm.query.vgirpc.schema.ProtocolName;
import farm.query.vgirpc.schema.ProtocolVersion;
import farm.query.vgirpc.schema.StreamHeader;

import java.util.List;
import java.util.Map;

/**
 * The {@code vgi.v2} protocol: every method a VGI worker serves, generated from
 * the reference ({@code vgi.protocol.VgiProtocol} in vgi-python).
 *
 * <p>vgi-rpc-java reflects over this interface to register the protocol, so the
 * declarations below <em>are</em> the wire contract: a parameter's Java type and
 * {@code @Nullable} derive its params-schema column, the return type derives the
 * {@code result} column, and {@code @StreamHeader} names a stream's header. They
 * reproduce the reference's schemas exactly, which is what makes
 * {@code vgi_rpc.Reflection.v1} report one {@code vgi.v2} hash in every SDK. The
 * protocol is the unit of optionality: every method is registered, whether or not
 * this worker implements it.</p>
 *
 * <p>Every method has a {@code default} body that answers {@code UNIMPLEMENTED} /
 * {@code method_not_implemented} with {@code "<method> is not implemented by this
 * worker"}; an implementation overrides the methods it serves. Never change a
 * signature here by hand: regenerate it, so the change comes from the protocol.</p>
 *
 * <p>Two parameter shapes coexist. <b>Packed</b> methods take one {@code request}
 * column holding an IPC-serialized record, bound either as the record itself or as
 * {@code byte[]} for the handler to decode. <b>Flat</b> methods map their
 * parameters 1:1 to columns by their {@code snake_case} name.</p>
 *
 * <p>{@link #PROTOCOL_NAME} is the wire identity: the {@code vgi_rpc.protocol}
 * routing key on every request and the protocol path segment over HTTP. It is
 * declared rather than derived because no Java identifier can spell it. The major
 * version is in the name, so an incompatible major is a different protocol (a 404
 * every proxy understands) and can be served beside this one.
 * {@link #PROTOCOL_VERSION} is what a client of this interface stamps on every
 * request; a VGI worker refuses a mismatched major+minor.</p>
 */
@ProtocolName(VgiService.PROTOCOL_NAME)
@ProtocolVersion(VgiService.PROTOCOL_VERSION)
public interface VgiService {

    /** The protocol's wire name: the {@code vgi_rpc.protocol} routing key. */
    String PROTOCOL_NAME = "vgi.v2";

    /** The protocol's semver, stamped on every request by a client of this interface. */
    String PROTOCOL_VERSION = "2.1.0";

    /**
     * Bind an aggregate function, return output schema and execution_id.
     *
     * <p>Wire method {@code aggregate_bind} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code AggregateBindRequest} ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default AggregateBindResponse aggregate_bind(
            AggregateBindRequest request,
            CallContext ctx) {
        throw notImplemented("aggregate_bind");
    }

    /**
     * Merge source states into target states.
     *
     * <p>Wire method {@code aggregate_combine} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code AggregateCombineRequest} ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default AggregateCombineResponse aggregate_combine(
            AggregateCombineRequest request,
            CallContext ctx) {
        throw notImplemented("aggregate_combine");
    }

    /**
     * Best-effort cleanup of aggregate states. Must not raise.
     *
     * <p>Wire method {@code aggregate_destructor} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code AggregateDestructorRequest} ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default AggregateDestructorResponse aggregate_destructor(
            AggregateDestructorRequest request,
            CallContext ctx) {
        throw notImplemented("aggregate_destructor");
    }

    /**
     * Produce results for a chunk of group_ids.
     *
     * <p>Wire method {@code aggregate_finalize} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code AggregateFinalizeRequest} ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default AggregateFinalizeResponse aggregate_finalize(
            AggregateFinalizeRequest request,
            CallContext ctx) {
        throw notImplemented("aggregate_finalize");
    }

    /**
     * Process one input chunk; returns one output row per input row.
     *
     * <p>Wire method {@code aggregate_streaming_chunk} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code AggregateStreamingChunkRequest}, as its IPC bytes
     *        ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default byte[] aggregate_streaming_chunk(
            byte[] request,
            CallContext ctx) {
        throw notImplemented("aggregate_streaming_chunk");
    }

    /**
     * End the streaming session, free per-session state.
     *
     * <p>Wire method {@code aggregate_streaming_close} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code AggregateStreamingCloseRequest}, as its IPC bytes
     *        ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default byte[] aggregate_streaming_close(
            byte[] request,
            CallContext ctx) {
        throw notImplemented("aggregate_streaming_close");
    }

    /**
     * Start a streaming-partitioned aggregate session.
     *
     * <p>Wire method {@code aggregate_streaming_open} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code AggregateStreamingOpenRequest}, as its IPC bytes
     *        ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default byte[] aggregate_streaming_open(
            byte[] request,
            CallContext ctx) {
        throw notImplemented("aggregate_streaming_open");
    }

    /**
     * Accumulate rows from a {@code DataChunk} into per-group state.
     *
     * <p>Wire method {@code aggregate_update} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code AggregateUpdateRequest} ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default AggregateUpdateResponse aggregate_update(
            AggregateUpdateRequest request,
            CallContext ctx) {
        throw notImplemented("aggregate_update");
    }

    /**
     * Compute an aggregate value for one output row of the window.
     *
     * <p>Wire method {@code aggregate_window} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code AggregateWindowRequest}, as its IPC bytes ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default byte[] aggregate_window(
            byte[] request,
            CallContext ctx) {
        throw notImplemented("aggregate_window");
    }

    /**
     * Compute {@code count} window output rows in one batched RPC.
     *
     * <p>Wire method {@code aggregate_window_batch} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code AggregateWindowBatchRequest}, as its IPC bytes
     *        ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default byte[] aggregate_window_batch(
            byte[] request,
            CallContext ctx) {
        throw notImplemented("aggregate_window_batch");
    }

    /**
     * Evict a cached partition from storage.
     *
     * <p>Wire method {@code aggregate_window_destructor} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code AggregateWindowDestructorRequest}, as its IPC bytes
     *        ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default byte[] aggregate_window_destructor(
            byte[] request,
            CallContext ctx) {
        throw notImplemented("aggregate_window_destructor");
    }

    /**
     * Ship a partition to the worker for windowed aggregation.
     *
     * <p>Wire method {@code aggregate_window_init} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code AggregateWindowInitRequest}, as its IPC bytes
     *        ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default byte[] aggregate_window_init(
            byte[] request,
            CallContext ctx) {
        throw notImplemented("aggregate_window_init");
    }

    /**
     * Resolve output schema and validate arguments.
     *
     * <p>Wire method {@code bind} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code BindRequest} ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default BindResponse bind(
            BindRequest request,
            CallContext ctx) {
        throw notImplemented("bind");
    }

    /**
     * Attach to a catalog with options.
     *
     * <p>Wire method {@code catalog_attach} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code CatalogAttachRequest} ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default CatalogAttachResult catalog_attach(
            CatalogAttachRequest request,
            CallContext ctx) {
        throw notImplemented("catalog_attach");
    }

    /**
     * List available catalog names.
     *
     * <p>Wire method {@code catalog_catalogs} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default ItemsResponse catalog_catalogs(
            CallContext ctx) {
        throw notImplemented("catalog_catalogs");
    }

    /**
     * Return every schema and all of its contents in one result.
     *
     * <p>Only called when the attach result sets {@code supports_catalog_contents}. Replaces
     * {@code catalog_schemas} plus every {@code catalog_schema_contents_*} call for a client that
     * wants the whole catalog. Takes no transaction: the client caches the answer catalog-wide, so
     * it is the committed catalog at {@code catalog_version}.
     *
     * <p>{@code if_none_match} is the {@code etag} of a snapshot the client holds. When it equals
     * the current etag the response is {@code not_modified} with no schemas. A worker that returns
     * {@code etag = None} ignores it.
     *
     * <p>Wire method {@code catalog_contents} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param if_none_match the {@code if_none_match} column ({@code string}, nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default CatalogContentsResponse catalog_contents(
            byte[] attach_opaque_data,
            @Nullable String if_none_match,
            CallContext ctx) {
        throw notImplemented("catalog_contents");
    }

    /**
     * List custom {@code COPY ... FROM} formats advertised by this catalog.
     *
     * <p>Catalog-level (not schema-scoped). Returns an empty list for catalogs with no custom
     * formats. Additive: workers that don't implement this method return
     * {@code MethodNotImplementedError}, which the VGI extension treats as "this catalog advertises
     * no COPY formats" and continues the ATTACH normally.
     *
     * <p>Wire method {@code catalog_copy_from_formats} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default ItemsResponse catalog_copy_from_formats(
            byte[] attach_opaque_data,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_copy_from_formats");
    }

    /**
     * Create a new catalog.
     *
     * <p>Wire method {@code catalog_create} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code CatalogCreateRequest}, as its IPC bytes ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_create(
            byte[] request,
            CallContext ctx) {
        throw notImplemented("catalog_create");
    }

    /**
     * Detach from a catalog.
     *
     * <p>Wire method {@code catalog_detach} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_detach(
            byte[] attach_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_detach");
    }

    /**
     * Drop a catalog.
     *
     * <p>Wire method {@code catalog_drop} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param name the {@code name} column ({@code string})
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_drop(
            String name,
            CallContext ctx) {
        throw notImplemented("catalog_drop");
    }

    /**
     * Create a new index.
     *
     * <p>Wire method {@code catalog_index_create} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code IndexCreateRequest}, as its IPC bytes ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_index_create(
            byte[] request,
            CallContext ctx) {
        throw notImplemented("catalog_index_create");
    }

    /**
     * Drop an index.
     *
     * <p>Wire method {@code catalog_index_drop} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param ignore_not_found the {@code ignore_not_found} column ({@code bool})
     * @param cascade the {@code cascade} column ({@code bool})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_index_drop(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            boolean ignore_not_found,
            boolean cascade,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_index_drop");
    }

    /**
     * Get information about an index. Returns 0 or 1 items.
     *
     * <p>Wire method {@code catalog_index_get} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default ItemsResponse catalog_index_get(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_index_get");
    }

    /**
     * Create a new macro.
     *
     * <p>Wire method {@code catalog_macro_create} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code MacroCreateRequest}, as its IPC bytes ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_macro_create(
            byte[] request,
            CallContext ctx) {
        throw notImplemented("catalog_macro_create");
    }

    /**
     * Drop a macro.
     *
     * <p>Wire method {@code catalog_macro_drop} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param ignore_not_found the {@code ignore_not_found} column ({@code bool})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_macro_drop(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            boolean ignore_not_found,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_macro_drop");
    }

    /**
     * Get information about a macro. Returns 0 or 1 items.
     *
     * <p>Wire method {@code catalog_macro_get} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default ItemsResponse catalog_macro_get(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_macro_get");
    }

    /**
     * List functions in a schema (scalar or table).
     *
     * <p>Wire method {@code catalog_schema_contents_functions} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param path the {@code path} column ({@code list<item: string>})
     * @param type the {@code type} column
     *        ({@code dictionary<values=string, indices=int16, ordered=0>})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default ItemsResponse catalog_schema_contents_functions(
            byte[] attach_opaque_data,
            List<String> path,
            @ArrowField(ArrowFieldType.DICT_INT16_UTF8) String type,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_schema_contents_functions");
    }

    /**
     * List indexes in a schema.
     *
     * <p>Wire method {@code catalog_schema_contents_indexes} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param path the {@code path} column ({@code list<item: string>})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default ItemsResponse catalog_schema_contents_indexes(
            byte[] attach_opaque_data,
            List<String> path,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_schema_contents_indexes");
    }

    /**
     * List macros in a schema (scalar or table).
     *
     * <p>Wire method {@code catalog_schema_contents_macros} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param path the {@code path} column ({@code list<item: string>})
     * @param type the {@code type} column
     *        ({@code dictionary<values=string, indices=int16, ordered=0>})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default ItemsResponse catalog_schema_contents_macros(
            byte[] attach_opaque_data,
            List<String> path,
            @ArrowField(ArrowFieldType.DICT_INT16_UTF8) String type,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_schema_contents_macros");
    }

    /**
     * List tables in a schema.
     *
     * <p>Wire method {@code catalog_schema_contents_tables} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param path the {@code path} column ({@code list<item: string>})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default ItemsResponse catalog_schema_contents_tables(
            byte[] attach_opaque_data,
            List<String> path,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_schema_contents_tables");
    }

    /**
     * List views in a schema.
     *
     * <p>Wire method {@code catalog_schema_contents_views} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param path the {@code path} column ({@code list<item: string>})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default ItemsResponse catalog_schema_contents_views(
            byte[] attach_opaque_data,
            List<String> path,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_schema_contents_views");
    }

    /**
     * Create a new schema.
     *
     * <p>Wire method {@code catalog_schema_create} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param path the {@code path} column ({@code list<item: string>})
     * @param on_conflict the {@code on_conflict} column
     *        ({@code dictionary<values=string, indices=int16, ordered=0>})
     * @param comment the {@code comment} column ({@code string}, nullable)
     * @param tags the {@code tags} column ({@code map<string, string>}, nullable)
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_schema_create(
            byte[] attach_opaque_data,
            List<String> path,
            @ArrowField(ArrowFieldType.DICT_INT16_UTF8) String on_conflict,
            @Nullable String comment,
            @Nullable Map<String, String> tags,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_schema_create");
    }

    /**
     * Drop a schema.
     *
     * <p>Wire method {@code catalog_schema_drop} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param path the {@code path} column ({@code list<item: string>})
     * @param ignore_not_found the {@code ignore_not_found} column ({@code bool})
     * @param cascade the {@code cascade} column ({@code bool})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_schema_drop(
            byte[] attach_opaque_data,
            List<String> path,
            boolean ignore_not_found,
            boolean cascade,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_schema_drop");
    }

    /**
     * Get information about a schema. Returns 0 or 1 items.
     *
     * <p>Wire method {@code catalog_schema_get} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param path the {@code path} column ({@code list<item: string>})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default ItemsResponse catalog_schema_get(
            byte[] attach_opaque_data,
            List<String> path,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_schema_get");
    }

    /**
     * List schemas in the catalog.
     *
     * <p>Wire method {@code catalog_schemas} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default ItemsResponse catalog_schemas(
            byte[] attach_opaque_data,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_schemas");
    }

    /**
     * Add a new column to a table.
     *
     * <p>Wire method {@code catalog_table_column_add} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param column_definition the {@code column_definition} column ({@code binary})
     * @param ignore_not_found the {@code ignore_not_found} column ({@code bool})
     * @param if_column_not_exists the {@code if_column_not_exists} column ({@code bool})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_table_column_add(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            byte[] column_definition,
            boolean ignore_not_found,
            boolean if_column_not_exists,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_table_column_add");
    }

    /**
     * Set or clear the comment on a table column.
     *
     * <p>Wire method {@code catalog_table_column_comment_set} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param column_name the {@code column_name} column ({@code string})
     * @param comment the {@code comment} column ({@code string}, nullable)
     * @param ignore_not_found the {@code ignore_not_found} column ({@code bool})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_table_column_comment_set(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            String column_name,
            @Nullable String comment,
            boolean ignore_not_found,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_table_column_comment_set");
    }

    /**
     * Remove the default value from a column.
     *
     * <p>Wire method {@code catalog_table_column_default_drop} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param column_name the {@code column_name} column ({@code string})
     * @param ignore_not_found the {@code ignore_not_found} column ({@code bool})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_table_column_default_drop(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            String column_name,
            boolean ignore_not_found,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_table_column_default_drop");
    }

    /**
     * Set the default value expression for a column.
     *
     * <p>Wire method {@code catalog_table_column_default_set} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param column_name the {@code column_name} column ({@code string})
     * @param expression the {@code expression} column ({@code string})
     * @param ignore_not_found the {@code ignore_not_found} column ({@code bool})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_table_column_default_set(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            String column_name,
            String expression,
            boolean ignore_not_found,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_table_column_default_set");
    }

    /**
     * Drop a column from a table.
     *
     * <p>Wire method {@code catalog_table_column_drop} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param column_name the {@code column_name} column ({@code string})
     * @param ignore_not_found the {@code ignore_not_found} column ({@code bool})
     * @param if_column_exists the {@code if_column_exists} column ({@code bool})
     * @param cascade the {@code cascade} column ({@code bool})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_table_column_drop(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            String column_name,
            boolean ignore_not_found,
            boolean if_column_exists,
            boolean cascade,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_table_column_drop");
    }

    /**
     * Rename a column.
     *
     * <p>Wire method {@code catalog_table_column_rename} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param column_name the {@code column_name} column ({@code string})
     * @param new_column_name the {@code new_column_name} column ({@code string})
     * @param ignore_not_found the {@code ignore_not_found} column ({@code bool})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_table_column_rename(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            String column_name,
            String new_column_name,
            boolean ignore_not_found,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_table_column_rename");
    }

    /**
     * Get column statistics for a table.
     *
     * <p>Returns IPC bytes of a {@code RecordBatch} with sparse-union min/max columns, or None if
     * statistics are not available.
     *
     * <p>Wire method {@code catalog_table_column_statistics_get} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary}, nullable)
     */
    @Nullable
    default byte[] catalog_table_column_statistics_get(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_table_column_statistics_get");
    }

    /**
     * Change the type of a column.
     *
     * <p>Wire method {@code catalog_table_column_type_change} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param column_definition the {@code column_definition} column ({@code binary})
     * @param expression the {@code expression} column ({@code string}, nullable)
     * @param ignore_not_found the {@code ignore_not_found} column ({@code bool})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_table_column_type_change(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            byte[] column_definition,
            @Nullable String expression,
            boolean ignore_not_found,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_table_column_type_change");
    }

    /**
     * Set or clear the comment on a table.
     *
     * <p>Wire method {@code catalog_table_comment_set} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param comment the {@code comment} column ({@code string}, nullable)
     * @param ignore_not_found the {@code ignore_not_found} column ({@code bool})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_table_comment_set(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            @Nullable String comment,
            boolean ignore_not_found,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_table_comment_set");
    }

    /**
     * Create a new table.
     *
     * <p>Wire method {@code catalog_table_create} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code TableCreateRequest}, as its IPC bytes ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_table_create(
            byte[] request,
            CallContext ctx) {
        throw notImplemented("catalog_table_create");
    }

    /**
     * Get the delete function for a table. Returns {@code WriteFunctionResult} as IPC bytes.
     *
     * <p>Wire method {@code catalog_table_delete_function_get} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default byte[] catalog_table_delete_function_get(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_table_delete_function_get");
    }

    /**
     * Drop a table.
     *
     * <p>Wire method {@code catalog_table_drop} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param ignore_not_found the {@code ignore_not_found} column ({@code bool})
     * @param cascade the {@code cascade} column ({@code bool})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_table_drop(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            boolean ignore_not_found,
            boolean cascade,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_table_drop");
    }

    /**
     * Get information about a table. Returns 0 or 1 items.
     *
     * <p>Wire method {@code catalog_table_get} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param at_unit the {@code at_unit} column ({@code string}, nullable)
     * @param at_value the {@code at_value} column ({@code string}, nullable)
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default ItemsResponse catalog_table_get(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            @Nullable String at_unit,
            @Nullable String at_value,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_table_get");
    }

    /**
     * Get the insert function for a table. Returns {@code WriteFunctionResult} as IPC bytes.
     *
     * <p>{@code writable_branch_function_name} is set by the C++ extension when the table is
     * multi-branch and a branch declared {@code writable=True}: the value is the writable arm's
     * {@code ScanBranch.function_name}. The worker uses it to disambiguate which physical arm to
     * dispatch the INSERT to without re-resolving the writable arm internally. For single-branch
     * tables (the common case) this is None and the worker dispatches as today.
     *
     * <p>Wire method {@code catalog_table_insert_function_get} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param writable_branch_function_name the {@code writable_branch_function_name} column
     *        ({@code string}, nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default byte[] catalog_table_insert_function_get(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            @Nullable byte[] transaction_opaque_data,
            @Nullable String writable_branch_function_name,
            CallContext ctx) {
        throw notImplemented("catalog_table_insert_function_get");
    }

    /**
     * Remove NOT NULL constraint from a column.
     *
     * <p>Wire method {@code catalog_table_not_null_drop} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param column_name the {@code column_name} column ({@code string})
     * @param ignore_not_found the {@code ignore_not_found} column ({@code bool})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_table_not_null_drop(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            String column_name,
            boolean ignore_not_found,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_table_not_null_drop");
    }

    /**
     * Add NOT NULL constraint to a column.
     *
     * <p>Wire method {@code catalog_table_not_null_set} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param column_name the {@code column_name} column ({@code string})
     * @param ignore_not_found the {@code ignore_not_found} column ({@code bool})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_table_not_null_set(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            String column_name,
            boolean ignore_not_found,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_table_not_null_set");
    }

    /**
     * Rename a table.
     *
     * <p>Wire method {@code catalog_table_rename} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param new_name the {@code new_name} column ({@code string})
     * @param ignore_not_found the {@code ignore_not_found} column ({@code bool})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_table_rename(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            String new_name,
            boolean ignore_not_found,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_table_rename");
    }

    /**
     * Get the list of scan branches for a multi-branch table. Returns {@code ScanBranchesResult} as
     * IPC bytes.
     *
     * <p>Additive successor to {@code catalog_table_scan_function_get}. Workers that only implement
     * the legacy method continue to work — the VGI extension's C++ side catches
     * {@code MethodNotImplementedError} and falls back to the legacy RPC, wrapping the
     * single-function result as a one-branch list. Workers that implement BOTH the legacy and the
     * branches method guarantee single-process compatibility with both old and new extensions.
     *
     * <p>Multi-branch tables compose a logical scan from N physical sources (canonical case: Kafka
     * hot tier + Iceberg cold tier). The extension's optimizer rewrite stitches the branches
     * together via {@code LogicalSetOperation(UNION_ALL, ...)}, one arm per branch.
     *
     * <p>Wire method {@code catalog_table_scan_branches_get} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param at_unit the {@code at_unit} column ({@code string}, nullable)
     * @param at_value the {@code at_value} column ({@code string}, nullable)
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default byte[] catalog_table_scan_branches_get(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            @Nullable String at_unit,
            @Nullable String at_value,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_table_scan_branches_get");
    }

    /**
     * Get the scan function for a table. Returns {@code ScanFunctionResult} as IPC bytes.
     *
     * <p>Wire method {@code catalog_table_scan_function_get} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param at_unit the {@code at_unit} column ({@code string}, nullable)
     * @param at_value the {@code at_value} column ({@code string}, nullable)
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default TableScanFunctionGetResponse catalog_table_scan_function_get(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            @Nullable String at_unit,
            @Nullable String at_value,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_table_scan_function_get");
    }

    /**
     * Get the update function for a table. Returns {@code WriteFunctionResult} as IPC bytes.
     *
     * <p>Wire method {@code catalog_table_update_function_get} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default byte[] catalog_table_update_function_get(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_table_update_function_get");
    }

    /**
     * Begin a new transaction.
     *
     * <p>Wire method {@code catalog_transaction_begin} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default TransactionBeginResponse catalog_transaction_begin(
            byte[] attach_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_transaction_begin");
    }

    /**
     * Commit a transaction.
     *
     * <p>Wire method {@code catalog_transaction_commit} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_transaction_commit(
            byte[] attach_opaque_data,
            byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_transaction_commit");
    }

    /**
     * Rollback a transaction.
     *
     * <p>Wire method {@code catalog_transaction_rollback} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_transaction_rollback(
            byte[] attach_opaque_data,
            byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_transaction_rollback");
    }

    /**
     * Get the current catalog version.
     *
     * <p>Wire method {@code catalog_version} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default CatalogVersionResponse catalog_version(
            byte[] attach_opaque_data,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_version");
    }

    /**
     * Set or clear the comment on a view.
     *
     * <p>Wire method {@code catalog_view_comment_set} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param comment the {@code comment} column ({@code string}, nullable)
     * @param ignore_not_found the {@code ignore_not_found} column ({@code bool})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_view_comment_set(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            @Nullable String comment,
            boolean ignore_not_found,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_view_comment_set");
    }

    /**
     * Create a new view.
     *
     * <p>Wire method {@code catalog_view_create} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param definition the {@code definition} column ({@code string})
     * @param on_conflict the {@code on_conflict} column
     *        ({@code dictionary<values=string, indices=int16, ordered=0>})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_view_create(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            String definition,
            @ArrowField(ArrowFieldType.DICT_INT16_UTF8) String on_conflict,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_view_create");
    }

    /**
     * Drop a view.
     *
     * <p>Wire method {@code catalog_view_drop} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param ignore_not_found the {@code ignore_not_found} column ({@code bool})
     * @param cascade the {@code cascade} column ({@code bool})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_view_drop(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            boolean ignore_not_found,
            boolean cascade,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_view_drop");
    }

    /**
     * Get information about a view. Returns 0 or 1 items.
     *
     * <p>Wire method {@code catalog_view_get} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default ItemsResponse catalog_view_get(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_view_get");
    }

    /**
     * Rename a view.
     *
     * <p>Wire method {@code catalog_view_rename} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param attach_opaque_data the {@code attach_opaque_data} column ({@code binary})
     * @param schema_path the {@code schema_path} column ({@code list<item: string>})
     * @param name the {@code name} column ({@code string})
     * @param new_name the {@code new_name} column ({@code string})
     * @param ignore_not_found the {@code ignore_not_found} column ({@code bool})
     * @param transaction_opaque_data the {@code transaction_opaque_data} column ({@code binary},
     *        nullable)
     * @param ctx the caller's context, injected by the server (not a wire field)
     */
    default void catalog_view_rename(
            byte[] attach_opaque_data,
            List<String> schema_path,
            String name,
            String new_name,
            boolean ignore_not_found,
            @Nullable byte[] transaction_opaque_data,
            CallContext ctx) {
        throw notImplemented("catalog_view_rename");
    }

    /**
     * Initialize a function execution and return a processing stream.
     *
     * <p>Wire method {@code init} (stream). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code InitRequest} ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the output stream, headed by a {@code GlobalInitResponse}
     */
    @StreamHeader(GlobalInitResponse.class)
    default RpcStream<? extends StreamState> init(
            InitRequest request,
            CallContext ctx) {
        throw notImplemented("init");
    }

    /**
     * Once-per-query end-of-input signal. Returns finalize_state_ids.
     *
     * <p>Wire method {@code table_buffering_combine} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code TableBufferingCombineRequest} ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default TableBufferingCombineResponse table_buffering_combine(
            TableBufferingCombineRequest request,
            CallContext ctx) {
        throw notImplemented("table_buffering_combine");
    }

    /**
     * Best-effort end-of-query cleanup. Must not raise.
     *
     * <p>Wire method {@code table_buffering_destructor} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code TableBufferingDestructorRequest} ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default TableBufferingDestructorResponse table_buffering_destructor(
            TableBufferingDestructorRequest request,
            CallContext ctx) {
        throw notImplemented("table_buffering_destructor");
    }

    /**
     * Sink one input batch; return the worker-chosen state_id.
     *
     * <p>Wire method {@code table_buffering_process} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code TableBufferingProcessRequest} ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default TableBufferingProcessResponse table_buffering_process(
            TableBufferingProcessRequest request,
            CallContext ctx) {
        throw notImplemented("table_buffering_process");
    }

    /**
     * Estimate the cardinality of a table function's output.
     *
     * <p>Wire method {@code table_function_cardinality} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code TableFunctionCardinalityRequest}, as its IPC bytes
     *        ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default CardinalityResponse table_function_cardinality(
            byte[] request,
            CallContext ctx) {
        throw notImplemented("table_function_cardinality");
    }

    /**
     * Return user-defined diagnostics for EXPLAIN ANALYZE Extra Info.
     *
     * <p>Fired once per parallel scan thread at end-of-stream. The function class is responsible
     * for persisting any diagnostics it wants to report and retrieving them by
     * {@code global_execution_id} here.
     *
     * <p>Best-effort: must not raise. The dispatcher catches exceptions and returns an empty
     * response so EXPLAIN ANALYZE never breaks the query.
     *
     * <p>Wire method {@code table_function_dynamic_to_string} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code TableFunctionDynamicToStringRequest}, as its IPC bytes
     *        ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default DynamicToStringResponse table_function_dynamic_to_string(
            byte[] request,
            CallContext ctx) {
        throw notImplemented("table_function_dynamic_to_string");
    }

    /**
     * Plan a table-function scan into named, independently redeemable splits.
     *
     * <p>Runs once with the pushdown filters; each returned split is then redeemed by
     * {@code init()} from any process or host. Workers that do not opt in via
     * {@code supports_splits} inherit a framework default.
     *
     * <p>Wire method {@code table_function_plan} (unary). Default: answers {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code TableFunctionPlanRequest}, as its IPC bytes ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary})
     */
    default PlanResponse table_function_plan(
            byte[] request,
            CallContext ctx) {
        throw notImplemented("table_function_plan");
    }

    /**
     * Return per-column statistics for a table function's output.
     *
     * <p>Returns IPC bytes of a {@code RecordBatch} with sparse-union min/max columns (same shape
     * as {@code catalog_table_column_statistics_get}), or None if no statistics are available.
     *
     * <p>Wire method {@code table_function_statistics} (unary). Default: answers
     * {@code UNIMPLEMENTED}.
     *
     * @param request the packed {@code TableFunctionStatisticsRequest}, as its IPC bytes
     *        ({@code binary})
     * @param ctx the caller's context, injected by the server (not a wire field)
     * @return the {@code result} column ({@code binary}, nullable)
     */
    @Nullable
    default byte[] table_function_statistics(
            byte[] request,
            CallContext ctx) {
        throw notImplemented("table_function_statistics");
    }

    /**
     * The error every method answers until an implementation overrides it.
     *
     * @param method the wire method name
     * @return {@code UNIMPLEMENTED} / {@code method_not_implemented}
     */
    private static MethodNotImplementedError notImplemented(String method) {
        return new MethodNotImplementedError(method + " is not implemented by this worker");
    }
}
